require:
  - rubocop-rspec

AllCops:
  Exclude:
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'spec/spec_helper.rb'
  NewCops: enable

# 日本語のコメントを許可
Style/AsciiComments:
  Enabled: false
