version: '3'
services:
  ruby:
    build: .
    command: sleep infinity
    ports:
      - 9292:9292
    environment:
      - POSTGRES_HOST=postgres
    volumes:
      - ${PWD}:/app
    working_dir: /app
  postgres:
    image: postgres:13.1-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=janken
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ${PWD}/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
