name: main

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0
        bundler-cache: true
    - run: ./bin/test.sh
    - uses: akhileshns/heroku-deploy@v3.10.9
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ruby-janken
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        dontuseforce: true
